# Utilisez une image Node.js
FROM node:16-alpine:000

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY backend/package*.json ./

# Nettoyer le cache npm
RUN npm cache clean --force

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY backend/ .

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3000

# Commande pour démarrer l'application avec npm start
CMD ["node", "app.js"]

